apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
  namespace: stream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      containers:
        - name: jobmanager
          image: allocknguyen/flink-ml-full:v2 
          args: ["jobmanager"]
          ports:
            - containerPort: 6123 # RPC
            - containerPort: 8081 # REST UI
            - containerPort: 6124 # Blob Server (Phải thêm cái này)
          volumeMounts:
            - name: config-volume
              mountPath: /opt/flink/conf/flink-conf.yaml
              subPath: flink-conf.yaml # Chỉ gắn file này
            - name: flink-config-volume
              mountPath: /opt/flink/usrlib/init.sql
              subPath: init.sql
            - name: flink-config-volume
              mountPath: /opt/flink/usrlib/fraud_prediction.py
              subPath: fraud_prediction.py
            - name: flink-config-volume
              mountPath: /opt/flink/usrlib/fraud_model.json
              subPath: fraud_model.json
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: config-volume
          configMap:
            name: flink-config
            items:
              - key: flink-conf.yaml
                path: flink-conf.yaml
        - name: flink-config-volume
          configMap:
            name: flink-config
